In [ ]:
#PES1UG20CS359
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_excel("MI_Assignment1_2_Online Retail.xlsx")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype         
---  ------       --------------   -----         
 0   InvoiceNo    541909 non-null  object        
 1   StockCode    541909 non-null  object        
 2   Description  540455 non-null  object        
 3   Quantity     541909 non-null  int64         
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64       
 6   CustomerID   406829 non-null  float64       
 7   Country      541909 non-null  object        
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB


In [ ]:
from pandas.core.algorithms import mode
import statistics

df['Description'].fillna(statistics.mode(df['Description']), inplace=True)
a = []
for i in df["CustomerID"]:
  if not np.isnan(i):
    a.append(i)
df["CustomerID"].fillna(float(mode(a)),inplace=True)
for i in df.index:
  if df['Quantity'][i] < 0:
    df['Quantity'][i]=df['Quantity'][i] * -1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':


In [ ]:
index = 0
for i in range(len(df)):
    if df['InvoiceDate'][i]> pd.Timestamp(2011,9,1):
        index = i
        break
df_ = df[:][:index]

In [ ]:
after = []
for i in df['CustomerID'][index+1:]:
    after.append(i)
len(after)    
after = np.array(after)
after = np.unique(after)

In [ ]:
lis=[0]*len(df_)
for i in range(len(df_)):
    if df_['CustomerID'][i] in after:
        lis[i]="Not Churn"
    else:
        lis[i]="Churn"
df_['Target'] = lis

In [ ]:
df_['Target']

0             Churn
1             Churn
2             Churn
3             Churn
4             Churn
            ...    
320700    Not Churn
320701    Not Churn
320702    Not Churn
320703    Not Churn
320704    Not Churn
Name: Target, Length: 320705, dtype: object

In [ ]:
df_ = df_[['Quantity', 'UnitPrice', 'Target']]
df_=df_.dropna()

In [ ]:
df_

Quantity  UnitPrice     Target
0              6       2.55      Churn
1              6       3.39      Churn
2              8       2.75      Churn
3              6       3.39      Churn
4              6       3.39      Churn
...          ...        ...        ...
320700         3       1.45  Not Churn
320701         1       3.95  Not Churn
320702         1       4.15  Not Churn
320703        12       1.45  Not Churn
320704         1      57.60  Not Churn

[320705 rows x 3 columns]

In [ ]:
x = df_.iloc[:,0:-1].values
y = df_.iloc[:,-1].values

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42)

In [ ]:
from sklearn.svm import SVC
model = SVC()
model.fit(x_train,y_train)

SVC()

In [ ]:
y_pred = model.predict(x_test)
y_pred

array(['Not Churn', 'Not Churn', 'Not Churn', ..., 'Not Churn',
       'Not Churn', 'Not Churn'], dtype=object)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_pred,y_test)

array([[    1,     2],
       [11063, 69111]])

In [ ]:
supportaccuracy = accuracy_score(y_pred,y_test)*100

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [ ]:
clf_entropy = DecisionTreeClassifier(criterion = "entropy", random_state = 100,max_depth = 6, min_samples_leaf = 5)
c=clf_entropy.fit(x_train, y_train)

In [ ]:
y_pred1 = c.predict(x_test)
print(y_pred1)

['Not Churn' 'Not Churn' 'Not Churn' ... 'Not Churn' 'Not Churn'
 'Not Churn']


In [ ]:
confusion_matrix(y_test, y_pred1)

array([[    0, 11064],
       [    0, 69113]])

In [ ]:
decisionaccuracy = accuracy_score(y_test,y_pred1)*100
decisionaccuracy

86.20053132444467

In [ ]:
classification_report(y_test, y_pred1)

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


'              precision    recall  f1-score   support\n\n       Churn       0.00      0.00      0.00     11064\n   Not Churn       0.86      1.00      0.93     69113\n\n    accuracy                           0.86     80177\n   macro avg       0.43      0.50      0.46     80177\nweighted avg       0.74      0.86      0.80     80177\n'

In [ ]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(15,), random_state=1)
clf.fit(x_train, y_train)
p2=clf.predict(x_test)

In [ ]:
confusion_matrix(y_test, p2)

array([[    1, 11063],
       [    2, 69111]])

In [ ]:
mlpaccuracy = accuracy_score(y_test,p2)*100

In [ ]:
classification_report(y_test, p2)

'              precision    recall  f1-score   support\n\n       Churn       0.33      0.00      0.00     11064\n   Not Churn       0.86      1.00      0.93     69113\n\n    accuracy                           0.86     80177\n   macro avg       0.60      0.50      0.46     80177\nweighted avg       0.79      0.86      0.80     80177\n'

In [ ]:
print(supportaccuracy,decisionaccuracy,mlpaccuracy)

86.19928408396423 86.20053132444467 86.19928408396423
